# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zecli-0.1.1-j151kxuEAAAi-URuk3YOrrJgD4spLoAvyj9fHbDR1sEo";
    path = fetchgit {
      url = "https://github.com/vrypan/zecli";
      rev = "97166c6df7e9d7423fcf6072b57313f42d5a3db7";
      hash = "sha256-0pi96Huxsq/7z5q3lC5swFInjhkwTsxItJFrGgxALCA=";
    };
  }
]
